if: tag != latest_develop # dont build for the latest_develop tagged version

dist: xenial
git:
  depth: false
language: go
go:
  - 1.11.x
services:
  - docker
addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
  - GO111MODULE=on
  - PGVER=12
  - PGPORT=5433
  - PGUSER=postgres
before_install:
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - nvm install 12
  - travis_retry make pre-ui
  - make generate
  - CI=false make ui-only
  #- go get -v github.com/mgechev/revive
before_script:
  - psql -c 'create database "stash-box-test";' -U postgres
  - psql -c 'CREATE EXTENSION pg_trgm;' -U postgres stash-box-test
script:
  # left lint off to avoid getting extra dependency
  #- make lint
  - make vet it
after_success:
  - docker pull stashapp/box-compiler:1
  - make cross-compile-docker-packr
before_deploy:
  # push the latest tag when on the develop branch
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then git tag -f latest_develop; git push -f --tags; fi
  - export RELEASE_DATE=$(date +'%Y-%m-%d %H:%M:%S %Z')
  - export STASH_VERSION=$(git describe --tags --exclude latest_develop)
  # set TRAVIS_TAG explcitly to the version so that it doesn't pick up latest_develop
  - if [ "$TRAVIS_BRANCH" = "master"]; then export TRAVIS_TAG=${STASH_VERSION}; fi
deploy:
  # latest develop release
  - provider: releases
    # use the v2 release provider for proper release note setting
    edge: true
    api_key:
      secure: Un4uHRIlkJswvdIbz9TH/lAmy6Fc4WAM+8A+CTIiHThAJrSKq07Bic940qj/8PFQTLvkJCrUDj5ZnCvFhrEVROlpqO2ByJcFdq7XtLJaZy8qsvlg6FA47MLDOyet4uin4RhIL0QQKg7xufU59beea7Bn5JXl97+yKBAd63X0AjyMirrG2tz+jrz5YMQh5IjIKOwJ78WY2vulw2DYxFnZc1a2qBJa3y1cI/V9MFpPL1IY92hmm5/P8PtEkq2QB1zdx3twzUdf/MovlpiQkb2e0GQ9NWbgL8fYRlB3uZVSpOWbBxIJ6Zqfrgd58JWUDrXYVrUeNScPFdjqKtkNE/Rmsqatm24YJ4yJ62Epb5BcY1g5/ZBkcuRPB8dSKDUkChxqgqTtSIwCWw7rIOJIx4KLxzBsOfJ3t6b3dC0RrKQWU+UWtUgjWqDHZOfq06AXi2XraHtkb9AxwnloNcXUAVUvsWAyViuKGmcCgRlBf66mrnUNqPew0JA2j/YLdkrebjnkBOj5CfP7QGkGbbubSSiWgOJ5Vdiclfo26+3aKEfz1U2AdMM33qJkErGRlx4CgTrQ8dyObcNf6uhScMNvn/qfBNkB86ujng1WIuaWMsoVd4dGuKq5lQhImklZow90KSbWBu9xBXSGgAB3Ewi4HaQ22m+zK059bqWCPjrwXlNY5LE=
    file:
    - dist/stashdb-osx
    - dist/stashdb-win.exe
    - dist/stashdb-linux
    skip_cleanup: true
    overwrite: true
    name: "${STASH_VERSION}: Latest development build"
    release_notes: "**${RELEASE_DATE}**\n This is always the latest committed version on the develop branch. Use as your own risk!"
    prerelease: true
    on:
      repo: stashapp/stash-box
      branch: develop
  # official master release - only build when tagged
  - provider: releases
    api_key:
      secure: Un4uHRIlkJswvdIbz9TH/lAmy6Fc4WAM+8A+CTIiHThAJrSKq07Bic940qj/8PFQTLvkJCrUDj5ZnCvFhrEVROlpqO2ByJcFdq7XtLJaZy8qsvlg6FA47MLDOyet4uin4RhIL0QQKg7xufU59beea7Bn5JXl97+yKBAd63X0AjyMirrG2tz+jrz5YMQh5IjIKOwJ78WY2vulw2DYxFnZc1a2qBJa3y1cI/V9MFpPL1IY92hmm5/P8PtEkq2QB1zdx3twzUdf/MovlpiQkb2e0GQ9NWbgL8fYRlB3uZVSpOWbBxIJ6Zqfrgd58JWUDrXYVrUeNScPFdjqKtkNE/Rmsqatm24YJ4yJ62Epb5BcY1g5/ZBkcuRPB8dSKDUkChxqgqTtSIwCWw7rIOJIx4KLxzBsOfJ3t6b3dC0RrKQWU+UWtUgjWqDHZOfq06AXi2XraHtkb9AxwnloNcXUAVUvsWAyViuKGmcCgRlBf66mrnUNqPew0JA2j/YLdkrebjnkBOj5CfP7QGkGbbubSSiWgOJ5Vdiclfo26+3aKEfz1U2AdMM33qJkErGRlx4CgTrQ8dyObcNf6uhScMNvn/qfBNkB86ujng1WIuaWMsoVd4dGuKq5lQhImklZow90KSbWBu9xBXSGgAB3Ewi4HaQ22m+zK059bqWCPjrwXlNY5LE=
    file:
    - dist/stashdb-osx
    - dist/stashdb-win.exe
    - dist/stashdb-linux
    # make the release a draft so the maintainers can confirm before releasing
    draft: true
    skip_cleanup: true
    overwrite: true
    # don't write the body. To be done manually for now. In future we might 
    # want to generate the changelog or get it from a file
    name: ${STASH_VERSION}
    on:
      repo: stashapp/stash-box
      tags: true
      # make sure we don't release using the latest_develop tag
      condition: $TRAVIS_TAG != latest_develop
